[build]
builder = "NIXPACKS"
buildCommand = "cd apps/api && yarn install && yarn build"

[deploy]
startCommand = "cd apps/api && node dist/main"
healthcheckPath = "/api/v1/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
